### ISSUE TITLE
Error: Cannot find module 'dotenv'

### ISSUE THREAD

**Issue by weaselfoot** [wayne530/twitter-wipe#1]
I'm not sure why I'm getting this error, this may be a stupid question, but where should I place the .env file? I have created it as a text file then saved as .env, with the values specified, in the /twitter-wipe/ directory. But when I try to run the code I get the above error. I guess it is related to the .env file, but not sure why. I am using a windows machine, if that has any effect

**Comment by wayne530** [comment]
Hi @weaselfoot, have you installed the project dependencies using `npm install`? If yes, would you mind checking your `node_modules/` directory to see if `dotenv` is in there? One thing you can try is to remove `node_modules/` and run `npm install` again. The `.env` file containing the credentials should be in the project's root directory.

**Comment by wayne530** [comment]
I haven't heard back from you so will assume you were able to resolve this issue. If not, feel free to open a new issue.

**Comment by weaselfoot** [comment]
Problem solved, as you say, I had missed the npm install. Thank you so much for this tool, it's very simple to use, especially with the built-in delay and retry
